/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeSubjectIdRouteImport } from './routes/practice.$subjectId'
import { Route as StudySubjectIdRouteImport } from './routes/study.$subjectId'
import { Route as StudySubjectIdUnitIdRouteImport } from './routes/study.$subjectId.$unitId'
import { Route as StudySubjectIdUnitIdTopicIdRouteImport } from './routes/study.$subjectId.$unitId.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeSubjectIdRoute = PracticeSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => PracticeRoute,
} as any)
const StudySubjectIdRoute = StudySubjectIdRouteImport.update({
  id: '/study/$subjectId',
  path: '/study/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySubjectIdUnitIdRoute = StudySubjectIdUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => StudySubjectIdRoute,
} as any)
const StudySubjectIdUnitIdTopicIdRoute =
  StudySubjectIdUnitIdTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => StudySubjectIdUnitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRouteWithChildren
  '/practice/$subjectId': typeof PracticeSubjectIdRoute
  '/study/$subjectId': typeof StudySubjectIdRouteWithChildren
  '/practice/': typeof PracticeIndexRoute
  '/study/$subjectId/$unitId': typeof StudySubjectIdUnitIdRouteWithChildren
  '/study/$subjectId/$unitId/$topicId': typeof StudySubjectIdUnitIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice/$subjectId': typeof PracticeSubjectIdRoute
  '/study/$subjectId': typeof StudySubjectIdRouteWithChildren
  '/practice': typeof PracticeIndexRoute
  '/study/$subjectId/$unitId': typeof StudySubjectIdUnitIdRouteWithChildren
  '/study/$subjectId/$unitId/$topicId': typeof StudySubjectIdUnitIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRouteWithChildren
  '/practice/$subjectId': typeof PracticeSubjectIdRoute
  '/study/$subjectId': typeof StudySubjectIdRouteWithChildren
  '/practice/': typeof PracticeIndexRoute
  '/study/$subjectId/$unitId': typeof StudySubjectIdUnitIdRouteWithChildren
  '/study/$subjectId/$unitId/$topicId': typeof StudySubjectIdUnitIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/practice/$subjectId'
    | '/study/$subjectId'
    | '/practice/'
    | '/study/$subjectId/$unitId'
    | '/study/$subjectId/$unitId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice/$subjectId'
    | '/study/$subjectId'
    | '/practice'
    | '/study/$subjectId/$unitId'
    | '/study/$subjectId/$unitId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/practice/$subjectId'
    | '/study/$subjectId'
    | '/practice/'
    | '/study/$subjectId/$unitId'
    | '/study/$subjectId/$unitId/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  StudySubjectIdRoute: typeof StudySubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/$subjectId': {
      id: '/practice/$subjectId'
      path: '/$subjectId'
      fullPath: '/practice/$subjectId'
      preLoaderRoute: typeof PracticeSubjectIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/study/$subjectId': {
      id: '/study/$subjectId'
      path: '/study/$subjectId'
      fullPath: '/study/$subjectId'
      preLoaderRoute: typeof StudySubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$subjectId/$unitId': {
      id: '/study/$subjectId/$unitId'
      path: '/$unitId'
      fullPath: '/study/$subjectId/$unitId'
      preLoaderRoute: typeof StudySubjectIdUnitIdRouteImport
      parentRoute: typeof StudySubjectIdRoute
    }
    '/study/$subjectId/$unitId/$topicId': {
      id: '/study/$subjectId/$unitId/$topicId'
      path: '/$topicId'
      fullPath: '/study/$subjectId/$unitId/$topicId'
      preLoaderRoute: typeof StudySubjectIdUnitIdTopicIdRouteImport
      parentRoute: typeof StudySubjectIdUnitIdRoute
    }
  }
}

interface PracticeRouteChildren {
  PracticeSubjectIdRoute: typeof PracticeSubjectIdRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeSubjectIdRoute: PracticeSubjectIdRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface StudySubjectIdUnitIdRouteChildren {
  StudySubjectIdUnitIdTopicIdRoute: typeof StudySubjectIdUnitIdTopicIdRoute
}

const StudySubjectIdUnitIdRouteChildren: StudySubjectIdUnitIdRouteChildren = {
  StudySubjectIdUnitIdTopicIdRoute: StudySubjectIdUnitIdTopicIdRoute,
}

const StudySubjectIdUnitIdRouteWithChildren =
  StudySubjectIdUnitIdRoute._addFileChildren(StudySubjectIdUnitIdRouteChildren)

interface StudySubjectIdRouteChildren {
  StudySubjectIdUnitIdRoute: typeof StudySubjectIdUnitIdRouteWithChildren
}

const StudySubjectIdRouteChildren: StudySubjectIdRouteChildren = {
  StudySubjectIdUnitIdRoute: StudySubjectIdUnitIdRouteWithChildren,
}

const StudySubjectIdRouteWithChildren = StudySubjectIdRoute._addFileChildren(
  StudySubjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRouteWithChildren,
  StudySubjectIdRoute: StudySubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
